language: rust
notifications:
    irc: "irc.mozilla.org#piston-internals"
    email:
        - mitchell.nordine@gmail.com
os:
    - linux
    - osx
env:
    global:
        - secure: F0lkJZqxOsdZpMv+Awwvl79JbLOuqMkeWENmiy5y8s9bjn+aSnch4GlmJJX7kWf/cr1IYqnb0RgVILDbJqj7rijsJ3DIDokgwDPZaz7iNr3RoGRArUN9RyKADVxUfvokNiaMpv6+59qCFqzSBmdGfvbgnkxJCyO6OpQVqk2pLns=
        - LD_LIBRARY_PATH: /usr/local/lib
install:
    - curl -O http://www.portaudio.com/archives/pa_stable_v19_20140130.tgz
    - tar xfz pa_stable_v19_20140130.tgz
    - (cd portaudio/ && ./configure && make && sudo make install)
before_script:
    - rustc --version
    - cargo --version
script:
    - cargo build -v
    - cargo test -v
    - cargo doc -v
after_success:
    - cp -R target/doc doc
    - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
    - rm -r doc
